
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionProvider from "@/_app/SessionProvider"
import { getSession } from "next-auth/react";
import dbConnect from "../../mongoose/connect";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const serverSession= await getSession();
  
  return (


    <html lang="en">
      <SessionProvider session={serverSession}>
        <body className={inter.className}>
          <main className="h-auto flex flex-col justify-center items-center">
            <Navbar />
            {children}
          </main>
        </body>
      </SessionProvider>
    </html>
  );
}
